const helper = {
  irregulars: {
    "faux pas": "faux",
    aircraft: "aircraft",
    alumna: "alumnae",
    alumnus: "alumni",
    analysis: "analyses",
    antenna: "antennae",
    antithesis: "antitheses",
    apex: "apices",
    appendix: "appendices",
    axis: "axes",
    bacillus: "bacilli",
    bacterium: "bacteria",
    basis: "bases",
    beau: "beaux",
    bison: "bison",
    bureau: "bureaux",
    cactus: "cacti",
    château: "châteaux",
    child: "children",
    codex: "codices",
    concerto: "concerti",
    corpus: "corpora",
    crisis: "crises",
    criterion: "criteria",
    curriculum: "curricula",
    datum: "data",
    deer: "deer",
    diagnosis: "diagnoses",
    die: "dice",
    dwarf: "dwarves",
    elf: "elves",
    ellipsis: "ellipses",
    erratum: "errata",
    fez: "fezzes",
    fish: "fish",
    focus: "foci",
    foot: "feet",
    formula: "formulae",
    fungus: "fungi",
    genus: "genera",
    goose: "geese",
    graffito: "graffiti",
    grouse: "grouse",
    half: "halves",
    hoof: "hooves",
    hypothesis: "hypotheses",
    index: "indices",
    knife: "knives",
    larva: "larvae",
    leaf: "leaves",
    libretto: "libretti",
    life: "lives",
    literature: "literature",
    loaf: "loaves",
    locus: "loci",
    louse: "lice",
    man: "men",
    matrix: "matrices",
    medium: "mediums",
    mouse: "mice",
    ox: "oxen",
    person: "people",
    tooth: "teeth",
    woman: "women",
  },

  getIrregulars() {
    return this.irregulars;
  },
};

export default helper;
